# Generated by Django 5.1.15 on 2026-06-06 15:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("is_customer", models.BooleanField(default=False)),
                ("is_supplier", models.BooleanField(default=False)),
                (
                    "tax_registration_number",
                    models.CharField(blank=True, max_length=32),
                ),
                ("country", models.CharField(blank=True, max_length=2)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("address", models.TextField(blank=True)),
                ("payment_terms_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="core.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "parties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="core.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="TaxCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vat", "VAT"),
                            ("sales", "Sales Tax"),
                            ("wht", "Withholding Tax"),
                            ("exempt", "Exempt"),
                            ("zero", "Zero-rated"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_codes",
                        to="core.company",
                    ),
                ),
                (
                    "input_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "output_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=64)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uoms",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[("stock", "Stock"), ("service", "Service")],
                        default="stock",
                        max_length=8,
                    ),
                ),
                (
                    "valuation_method",
                    models.CharField(
                        choices=[
                            ("fifo", "FIFO"),
                            ("moving_average", "Moving Average"),
                        ],
                        default="moving_average",
                        max_length=16,
                    ),
                ),
                ("hsn_sac_code", models.CharField(blank=True, max_length=16)),
                (
                    "standard_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "sales_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.company",
                    ),
                ),
                (
                    "sales_tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masterdata.taxcode",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="masterdata.unitofmeasure",
                    ),
                ),
            ],
            options={
                "ordering": ["sku"],
                "unique_together": {("company", "sku")},
            },
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="masterdata.item",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="masterdata.pricelist",
                    ),
                ),
            ],
            options={
                "unique_together": {("price_list", "item")},
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=64)),
                ("address", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
    ]
