# Generated by Django 5.1.15 on 2026-06-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="masterdata.party",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("company", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="accountingperiod",
            unique_together={("company", "name")},
        ),
    ]
