# Generated by Django 5.1.15 on 2026-06-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EInvoiceSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=2)),
                ("adapter", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cleared", "Cleared / Reported"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("request_payload", models.TextField(blank=True)),
                ("response_payload", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="einvoice_submissions",
                        to="core.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="orders.customerinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
