# Generated by Django 5.1.15 on 2026-06-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="einvoicesubmission",
            name="invoice",
        ),
        migrations.AddField(
            model_name="einvoicesubmission",
            name="document_id",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="einvoicesubmission",
            name="document_type",
            field=models.CharField(default="customer_invoice", max_length=40),
        ),
    ]
