# Generated by Django 5.1.15 on 2026-06-06 15:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.CharField(blank=True, max_length=40)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_moves",
                        to="core.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_moves",
                        to="masterdata.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_moves",
                        to="masterdata.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockValuationLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("remaining_qty", models.DecimalField(decimal_places=4, max_digits=18)),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "remaining_value",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_layers",
                        to="core.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_layers",
                        to="masterdata.item",
                    ),
                ),
                (
                    "source_move",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.stockmove",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_layers",
                        to="masterdata.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
