# Generated by Django 5.1.15 on 2026-06-10 16:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("core", "0002_documentsequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("useful_life_months", models.PositiveSmallIntegerField(default=60)),
                ("asset_account_code", models.CharField(default="1510", max_length=20)),
                (
                    "accum_depreciation_code",
                    models.CharField(default="1520", max_length=20),
                ),
                (
                    "expense_account_code",
                    models.CharField(default="5300", max_length=20),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_categories",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "asset categories",
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("acquisition_date", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("useful_life_months", models.PositiveSmallIntegerField()),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disposed", "Disposed")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "acquisition_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_assets",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ["company", "name"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_entries",
                        to="assets.fixedasset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "depreciation entries",
                "ordering": ["period"],
                "unique_together": {("asset", "period")},
            },
        ),
    ]
